import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import worker,{validate,ingest} from '../cloudflare/worker.mjs';
const fixture=()=>({...JSON.parse(readFileSync(new URL('../examples/report-template.json',import.meta.url))),items:[{id:'test',stock_codes:['0286'],company_names:['Synthetic company'],category:'test',headline:'Test only',facts:['Synthetic'],analysis:[],catalysts:[],risks:[],sources:[{url:'https://example.com',title:'Synthetic',published_at:null}],verification_status:'synthetic'}]});
function db(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../migrations/0001_research.sql',import.meta.url),'utf8'));return {prepare(q){let args=[];return {bind(...a){args=a;return this;},async run(){const r=sql.prepare(q).run(...args);return {meta:{changes:Number(r.changes)}}},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}}}}};}
test('preserves leading zeros; rejects unsafe links and impossible dates',()=>{assert.equal(validate(JSON.stringify(fixture())).items[0].stock_codes[0],'0286');let r=fixture();r.items[0].sources[0].url='javascript:alert(1)';assert.throws(()=>validate(JSON.stringify(r)));r=fixture();r.report_date='2026-02-30';assert.throws(()=>validate(JSON.stringify(r)));});
test('D1-compatible SQL preserves revisions and suppresses repeated reports',async()=>{const d=db();let r=fixture();assert.equal((await ingest(d,JSON.stringify(r))).status,'imported');assert.equal((await ingest(d,JSON.stringify(r))).status,'duplicate');r.items[0].facts=['Revision'];assert.equal((await ingest(d,JSON.stringify(r))).status,'imported');assert.equal((await d.prepare('SELECT * FROM reports').all()).results.length,2);});
test('invalid batch never writes',async()=>{const d=db(),r=fixture();r.items.push({...r.items[0],id:'bad',stock_codes:[286]});await assert.rejects(ingest(d,JSON.stringify(r)));assert.equal((await d.prepare('SELECT * FROM reports').all()).results.length,0);});
test('API authentication and pagination',async()=>{const DB=db(),APP_TOKEN='a'.repeat(30),env={DB,APP_TOKEN};assert.equal((await worker.fetch(new Request('https://local/api/research'),env)).status,401);await ingest(DB,JSON.stringify(fixture()));const r=await worker.fetch(new Request('https://local/api/research',{headers:{Authorization:'Bearer '+APP_TOKEN}}),env);const s=await r.json();assert.equal(s.items.length,1);assert.equal(s.next_offset,null);});
